#!/bin/bash

LOCALIP=`ip a | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`
browser-sync start \
  -s ./public \
  -f ./public \
  --no-notify \
  --host $LOCALIP \
  --port 9000
